# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Prototype Pin Blog
tagline:          The Blog for Prototype Pin
url:              http://blog.prototypepin.com
paginate:         1
baseurl:          /
author:
  name:           Prototype Pin
  url:            https://twitter.com/prototypepin
  email:          thsonvt@gmail.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml' 